# .travis.yml

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh github_package testthat
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package berndbischl/BBmisc
  - ./travis-tool.sh github_package berndbischl/parallelMap
  - ./travis-tool.sh github_package berndbischl/ParamHelpers
  - ./travis-tool.sh r_install soobench
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
